/run/numberOfThreads 12
/run/initialize
/ENUTAG/testMode true
/ENUTAG/outName ../ROOT/testOut.root
/vis/open OGL 600x600-0+0

/control/execute graphics.mac

/vis/geometry/set/visibility logicConcrete0 0 false
/vis/geometry/set/visibility logicConcreteD1 0 false
/vis/geometry/set/visibility logicConcrete1 0 false
/vis/geometry/set/visibility logicConcreteD2 0 false
/vis/geometry/set/visibility logicConcrete2 0 false
/vis/geometry/set/visibility logicConcreteS0 0 false
/vis/geometry/set/visibility logicConcreteS1 0 false
/vis/geometry/set/visibility logicConcreteS2 0 false
/vis/geometry/set/visibility logicConcreteSD1L 0 false
/vis/geometry/set/visibility logicConcreteSD1R 0 false
/vis/geometry/set/visibility logicConcreteSD2L 0 false
/vis/geometry/set/visibility logicConcreteSD2R 0 false
/vis/geometry/set/visibility logicConcreteTARGET 0 false
/vis/geometry/set/visibility logicConcreteCLOSE 0 false

/vis/geometry/set/visibility logicTungstenCLOSE 0 0.15 0.3 0 false
/vis/geometry/set/visibility logicTungstenInline1 0 0.15 0.3 0 false
/vis/geometry/set/visibility logicTungstenSD1R 0 0.15 0.3 0 false
/vis/geometry/set/visibility logicTungstenSD1L 0 0.15 0.3 0 false
/vis/geometry/set/visibility logicTungstenInline2 0 0.15 0.3 0 false
/vis/geometry/set/visibility logicTungstenS1 0 0.15 0.3 0 false
/vis/geometry/set/visibility logicTungstenSD2R 0 0.15 0.3 0 false
/vis/geometry/set/visibility logicTungstenSD2L 0 0.15 0.3 0 false