/run/numberOfThreads 12
/run/initialize
/ENUTAG/testMode false
/ENUTAG/outName ../ROOT/visOut.root
/vis/open OGL 600x600-0+0

/control/execute graphics.mac

/vis/scene/endOfEventAction accumulate -1

/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#/vis/filtering/trajectories/particleFilter-0/add e+
#/vis/filtering/trajectories/particleFilter-0/add e-
#/vis/filtering/trajectories/particleFilter-0/add neutrino
/vis/filtering/trajectories/particleFilter-0/add proton
#/vis/filtering/trajectories/particleFilter-0/add neutron
/vis/filtering/trajectories/particleFilter-0/add pi+
#/vis/filtering/trajectories/particleFilter-0/add pi-
/vis/filtering/trajectories/particleFilter-0/add kaon+
#/vis/filtering/trajectories/particleFilter-0/add kaon-
/vis/filtering/trajectories/particleFilter-0/invert false
/vis/filtering/trajectories/particleFilter-0/active true